### ISSUE TITLE
Default Values don't appear

### ISSUE THREAD

**Issue by johnpap21** [moodleuulm/moodle-local_profilecohort#17] opened 2018-11-29 10:40 UTC
Hello

We have set some default values for our Custom Fields.  When we assign these field values to the learners, nothing seems to assign the cohorts, however, if we export the data and then reimport it using a UTF-8 CSV file, then it assigns the relevant information to the cohort.

For example - 
Internal staff - Employed
Contractors - Contractor
External Users - External

We don't get everything imported, as we have 8 admin users, so these get left behind - and these are not synchronised to the Employed cohort.

Thanks in Advanced
John

**Comment by bfriesenvcc** [comment] 2018-12-04 18:33
I'm also having some issues where my fields don't seem to get recognized. Mine are with a checkbox field and a drop-down option field.  My text fields seem to work.  What type of fields are yours, out of curiosity.

**Comment by johnpap21** [comment] 2018-12-06 09:51
Hi bfriesenvcc

I have tried checkbox, dropdown as well as text fields.

I have found however, that if I populate with default entries, then export and reimport they start to sync, or if a learner goes in and edits the field and saves, however, this isn't really the way it should operate.

I am using Moodle 3.5.2

Regards
john

**Comment by johnpap21** [comment] 2018-12-06 09:51
> I'm also having some issues where my fields don't seem to get recognized. Mine are with a checkbox field and a drop-down option field. My text fields seem to work. What type of fields are yours, out of curiosity.

Hi bfriesenvcc

I have tried checkbox, dropdown as well as text fields.

I have found however, that if I populate with default entries, then export and reimport they start to sync, or if a learner goes in and edits the field and saves, however, this isn't really the way it should operate.

I am using Moodle 3.5.2

**Comment by abias** [comment] 2019-03-25 10:31
Hi all,
as mentioned in https://github.com/moodleuulm/moodle-local_profilecohort/issues/14#issuecomment-354243603, there are currently two triggers which update a cohort membership within the plugin:
* The cohort memberships of a certain user are updated when a user logs in
* The cohort memberships of all users are updated with a scheduled task which runs every 5 minutes by default (see https://github.com/moodleuulm/moodle-local_profilecohort/blob/master/db/tasks.php)

#14 will deal with the fact that cohort memberships should also be updated when a user is created and his profile fields are updated.

Could you please check in your scenario if the cohorts are really not set after the user has logged in?

Cheers,
Alex

**Comment by abias** [comment] 2019-03-25 13:19
Please note that #14 has just been resolved and the plugin now also updates the cohorts when users are created or profile fields are updated. I hope that this change also will fix this issue.

**Comment by bfriesenvcc** [comment] 2019-03-25 16:23
Hi, abias.

It's been a while since I've looked at this, or even thought about it, but I *believe* that the issue I was experiencing may have been only with the cron job, and not when a user logged on.  I will try to test, soon.

**Comment by abias** [comment] 2019-04-08 10:17
Thanks for your feedback.

I am leaving this issue open for some more days to see if you still can reproduce your problem. If you can, please provide detailed steps to reproduce the problem on a fresh Moodle installation so that I reproduce it here, too.

Thanks,
Alex

**Comment by johnpap21** [comment] 2019-04-08 10:37
Alex

Essentially if we have a default in a field - say the company name.  This could be ACME and this be in either a Text Entry or Text Field, this does not always add the learner into the cohort, unless you either edit the record and retype the company name OR if you export the learners and reimport them through bulk import and export.

Hope that helps.

John

**Comment by abias** [comment] 2019-07-08 09:49
Hi John,

sorry for my late reply again.

While I don't want to state that something like that what you describe can't happen, I am struggling to reproduce it locally and would be looking for steps to reproduce.

This is what I just ran successfully in our Moodle production instance:
* Get a Moodle instance with many users, and existing and filled custom profile fields
* Login as admin
* Go to /cohort/index.php
* Create a cohort
* Go to /local/profilecohort/cohorts.php
* Mark the new cohort as managed
* Go to /local/profilecohort/index.php?action=add
* Create a rule for any custom profile field of type "text" and set a matching criteria where a large set of users has a matching custom profile field value
* Save the page
* Go to /local/profilecohort/index.php?action=members
** Expected result: The number of cohort members in the new cohort is zero or really low
* Go to /cohort/index.php
** Expected result: The number of cohort members in the new cohort is zero or really low
* Go to /admin/tool/task/scheduledtasks.php
* Run the \local_profilecohort\task\update_cohorts task manually and wait until it finishes
* Go to /local/profilecohort/index.php?action=members again
** Expected result: The number of cohort members in the new cohort is matching the number of users which have the matching criteria in their custom profile field
* Go to /cohort/index.php again
** Expected result: The number of cohort members in the new cohort is matching the number of users which have the matching criteria in their custom profile field

John,
please make sure that the task \local_profilecohort\task\update_cohorts has run at least once before you check the cohort members because this task is the only responsible piece of code to add the cohort members for "stale" users (i.e. users who did not log in recently or have been updated recently).
If you can confirm the problem after the task has been run, please let me know where your scenario diverges from mine.

Chers,
Alex

**Comment by abias** [comment] 2019-07-27 07:49
Hi John,

are there any news on your side?

Thanks,
Alex

**Comment by abias** [comment] 2019-10-24 05:10
As there wasn't any answer anymore about this issue, I will close it now.

Please don't hesitate to come back to me if there are any further problems.

Cheers,
Alex

**Closed by abias** 2019-10-24 05:10 UTC
